name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Install
        run: pip install -r requirements.txt
      - name: Test
        run: python Test.py
